# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='answer_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
